name: fortaleza_maker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bluetooth_low_energy: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Stencil
      fonts:
        - asset: assets/AllertaStencil-Regular.ttf
          weight: 400